### ISSUE TITLE
ヘッダファイルのインストール先がおかしい

### ISSUE THREAD

**Issue by shinsuke-ota** [artemis-dev/artemis#41]
b140bd6　を用いてコンパイル、インストールをスクラッチから行ったところ、ヘッダファイルのインストール先が $CMAKE_INSTALL_PREFIX/sources/... などとなってしまって、元のソースディレクトリの構造を保存したままになってしまっているようです。

**Comment by rin-yokoyama** [comment]
@shinsuke-ota 確か元のリポジトリに使われていないファイルが残っており、そのままだとsources/ artemis-share/ cat-src/間で競合があって一か所にインストールできなかったので、後にディレクトリ構造を含め整理を行うつもりで今の状態になっています。至急解決する必要があれば問題のあるヘッダーファイルのみ探して削除して一か所にインストールするようにしますがいかがですか？
cmake を使う場合 find_package(artemis) すると自動でincludeが設定されるのであまり問題視していませんでした・・・

**Comment by shinsuke-ota** [comment]
@rin-yokoyama なるほど。そのあたりを整理しないとだめだったという。ひとまず至急ではないのですが、.C+ とかでマクロを aclic でコンパイルするときに　artemis のクラスを使う場合には問題が出てくるかなと思います。
（cmake に統一するのであれば便利ですね。)

もしやってもらえるのであれば、削除するまえにひとまずどのファイルが競合するかを教えてもらえると嬉しいです。

**Comment by rin-yokoyama** [comment]
競合があるファイルは削除しました。
まだ多少artemis-shareに使われていないファイルは残っています。
@shinsuke-ota にreview requestしました。

**Comment by rin-yokoyama** [comment]
masterにpull request していたので developにやり直しました。#44 でお願いします。
